spring:
  profiles: default
server:
  port: 8010
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
  # Allow Eureka to recognize two apps of the same type on the same host as separate instances:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  
---  
spring:
  profiles: primary
server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/,http://localhost:8010/eureka/

---
spring:
  profiles: secondary
server:
  port: 8012
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/,http://localhost:8010/eureka/
      
---
spring:
  profiles: tertiary
server:
  port: 8013
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://localhost:8010/eureka/