eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: subject
  application: 
    name: lab-4-subject
server:
  port: ${PORT:${SERVER_PORT:0}}
words: I,You,He,She,It

#Utilzando o arquivo com profile (lab-verb.yml)
#---
#spring:
#  profiles: verb
#words: ran,knew,had,saw,bought
---
spring:
  profiles: verb
  application:
    name: lab-4-verb
server:
  port: ${PORT:${SERVER_PORT:0}}
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application: 
    name: lab-4-article
server:
  port: ${PORT:${SERVER_PORT:0}}
words: a,the

---
spring:
  profiles: adjective
  application: 
    name: lab-4-adjective
server:
  port: ${PORT:${SERVER_PORT:0}}
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application: 
    name: lab-4-noun
server:
  port: ${PORT:${SERVER_PORT:0}}
words: boat,book,vote,seat,backpack,partition,groundhog 
