#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/
      
server:
  #port: 8001
  port: ${PORT:${SERVER_PORT:0}}

#spring:
  #profiles: verb
    #active: default
     
#words: ran,knew,had,saw,bought